import os
import sys
import time
import base64
import tempfile
import subprocess
import requests
import hashlib
import hmac
import json

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

OUTPUT_DIR = os.path.join(tempfile.gettempdir(), "reels-generator")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Global: last video prompt generated by Claude (for Hokan paired prompts)
_last_claude_video_prompt = ""

def get_last_claude_video_prompt() -> str:
    return _last_claude_video_prompt


# ===== STYLE PROMPTS =====

_PROMPTS_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "prompts", "prompts.json")

# Fallback якщо файл відсутній
_FALLBACK_PROMPTS = {
    "Самурай": "RAW photo, 85mm portrait lens f/1.8, fearsome Japanese samurai warrior, red lacquered o-yoroi armor, hannya oni mask, deer antlers on kabuto, misty battlefield, volumetric fog, photorealistic, Kodak film grain, NOT illustration, NOT CGI",
    "Ніндзя": "RAW photo, 85mm lens f/1.8, ninja warrior in black armor, glowing red eyes, dark rainy night, neon reflections, volumetric fog, photorealistic, NOT illustration",
    "Лицар": "RAW photo, 85mm lens f/2, dark knight in gothic plate armor, castle ruins, torch light, fog, photorealistic, NOT illustration",
    "Воїн": "RAW photo, 85mm lens f/1.8, barbarian warrior, war paint, fur armor, dark battlefield, photorealistic, NOT illustration",
    "Спартанець": "RAW photo, 85mm lens f/2, Spartan warrior in bronze armor, cliff edge, stormy sea, 300-movie style, photorealistic, NOT illustration",
}


def load_prompts() -> dict:
    """Завантажує промпти з prompts.json."""
    try:
        with open(_PROMPTS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {"styles": {}}


def save_prompts(data: dict) -> bool:
    """Зберігає промпти в prompts.json."""
    try:
        with open(_PROMPTS_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        return True
    except Exception:
        return False


def get_style_prompt(style: str, variant_index: int = -1) -> str:
    """Повертає промпт для стилю. variant_index=-1 = випадковий."""
    import random
    data = load_prompts()
    styles = data.get("styles", {})
    style_data = styles.get(style)
    if style_data:
        variants = style_data.get("variants", [])
        if variants:
            if variant_index >= 0 and variant_index < len(variants):
                return variants[variant_index]["prompt"]
            return random.choice(variants)["prompt"]
    return _FALLBACK_PROMPTS.get(style, _FALLBACK_PROMPTS["Самурай"])


# ===== CLAUDE PROMPT GENERATION =====

def _load_master_prompt() -> dict:
    """Завантажує mushin master prompt якщо є."""
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "prompts", "mushin_master_prompt.json")
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def _load_hokan_master_prompt() -> str:
    """Load Hokan master prompt from markdown file."""
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "prompts", "hokan_master_prompt.md")
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except Exception:
        return ""


def _find_claude_cli() -> str:
    """Find Claude CLI binary."""
    import glob as _glob
    import shutil as _shutil
    # 1. Bundled у папці python/ поруч з generate.py
    local_exe = os.path.join(os.path.dirname(os.path.abspath(__file__)), "claude.exe")
    if os.path.isfile(local_exe):
        return local_exe
    # 2. PATH (npm global install, etc.)
    for name in ("claude.cmd", "claude.exe", "claude"):
        found = _shutil.which(name)
        if found:
            return found
    # 3. Direct known path
    known = os.path.expanduser(r"~\AppData\Roaming\Claude\claude-code")
    if os.path.isdir(known):
        for d in sorted(os.listdir(known), reverse=True):
            exe = os.path.join(known, d, "claude.exe")
            if os.path.isfile(exe):
                return exe
    # 4. Glob fallback
    for pattern in [
        os.path.expanduser("~/AppData/Roaming/Claude/claude-code/*/claude.exe"),
        os.path.expanduser("~/AppData/Local/Programs/claude/claude.exe"),
    ]:
        matches = sorted(_glob.glob(pattern), reverse=True)
        if matches:
            return matches[0]
    return ""


def _assemble_image_prompt(img: dict) -> str:
    """Повертає image_prompt як JSON string для Nano Banana Pro формату.

    Якщо промпт вже у Nano Banana Pro форматі (має поля Style, Subject, MadeOutOf тощо),
    повертає JSON as-is. Інакше збирає з legacy полів.
    """
    # Nano Banana Pro format — повертаємо JSON as-is
    if img.get("Style") or img.get("Subject") or img.get("MadeOutOf"):
        return json.dumps(img, ensure_ascii=False, indent=2)

    # Legacy format — збираємо текст для сумісності
    parts = []
    angle = img.get("angle", "")
    if angle:
        parts.append(f"FRAMING: {angle}.")
    if img.get("camera"):
        parts.append(img["camera"] + ".")
    if img.get("persona"):
        parts.append(f"Subject: fictional {img['persona']} warrior character.")
    if img.get("character_description"):
        parts.append(img["character_description"])
    if img.get("location"):
        parts.append(img["location"] + ".")
    if img.get("weather"):
        parts.append(img["weather"] + ".")
    if img.get("scene_description"):
        parts.append(img["scene_description"])
    return " ".join(parts) if parts else ""


def _assemble_video_prompt(vid: dict) -> str:
    """Збирає video_prompt JSON полів в один текстовий промпт."""
    # scene_description вже містить повний промпт
    if vid.get("scene_description"):
        return vid["scene_description"]
    parts = []
    parts.append("Cinematic slow motion. A continuous single unbroken shot.")
    if vid.get("lighting"):
        parts.append(vid["lighting"] + ".")
    if vid.get("camera_movement"):
        parts.append(vid["camera_movement"] + ".")
    if vid.get("weather_description"):
        parts.append(vid["weather_description"] + ".")
    if vid.get("character_behavior"):
        parts.append(vid["character_behavior"] + ".")
    parts.append("Everything moves at half speed, smooth and fluid. No flashes no explosions no bright light no fire no god rays at any point. The lighting stays exactly the same from first frame to last frame.")
    return " ".join(parts)


def _parse_claude_response(text: str, style: str) -> str | None:
    """Parse Claude response — handles both new JSON structure and legacy flat format."""
    global _last_claude_video_prompt
    try:
        import re
        m = re.search(r'\{.*\}', text, re.DOTALL)
        if m:
            data = json.loads(m.group())
            img = data.get("image_prompt", "")
            vid = data.get("video_prompt", "")

            # New structured format: image_prompt is a dict with fields
            if isinstance(img, dict):
                _last_claude_video_prompt = _assemble_video_prompt(vid) if isinstance(vid, dict) else str(vid)
                return _assemble_image_prompt(img)
            # Legacy flat format: image_prompt is a string
            else:
                _last_claude_video_prompt = _assemble_video_prompt(vid) if isinstance(vid, dict) else str(vid)
                return str(img) if img else text
    except Exception:
        pass
    _last_claude_video_prompt = ""
    return text


# --- Diversity tracking ---
_HISTORY_FILE = os.path.join(OUTPUT_DIR, "_prompt_history.json")
_MAX_HISTORY = 12


def _load_history() -> list[dict]:
    try:
        if os.path.isfile(_HISTORY_FILE):
            with open(_HISTORY_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
    except Exception:
        pass
    return []


def _save_history(history: list[dict]):
    try:
        os.makedirs(os.path.dirname(_HISTORY_FILE), exist_ok=True)
        with open(_HISTORY_FILE, "w", encoding="utf-8") as f:
            json.dump(history[-_MAX_HISTORY:], f, ensure_ascii=False, indent=2)
    except Exception:
        pass


def _pick_diverse(options: list[str], key: str, history: list[dict]) -> str:
    """Pick a random option avoiding recent history for this key."""
    import random
    recent = [h.get(key) for h in history[-5:]]
    available = [o for o in options if o not in recent]
    if not available:
        available = options
    return random.choice(available)


def generate_prompt_for_style(style: str) -> dict | None:
    """Generate image+video+quote prompts via Claude CLI for the given style.
    Loads master prompt from python/prompts/{style.lower()}_master_prompt.md
    Returns dict with image_prompt, video_prompt, quote — or None on failure.
    """
    prompts_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "prompts")
    master_path = os.path.join(prompts_dir, f"{style.lower()}_master_prompt.md")

    if not os.path.isfile(master_path):
        print(f"[Claude] Master prompt not found: {master_path}", flush=True)
        return None

    with open(master_path, "r", encoding="utf-8") as f:
        master = f.read()

    # Per-style variety options
    _VARIETY = {
        "hokan": {
            "warriors":    ["samurai with oni mask", "ronin with scarred face no mask", "ashigaru foot soldier with banner", "sohei warrior monk with naginata", "shogun warlord mounted on horse", "shinobi assassin crouching at night"],
            "backgrounds": ["dark misty forest", "devastated battlefield", "snowy mountain blizzard", "destroyed temple in rain", "stone torii gate in fog", "wooden bridge over gorge", "dark Japanese garden", "bamboo grove in rain", "burning castle ruins"],
            "angles":      ["close-up from chest up side profile", "extreme close-up of mask only", "full body dramatic low angle", "medium shot from behind", "low angle looking up at mounted warrior"],
        },
        "mushin": {
            "warriors":    ["armored samurai matte black armor oni mask", "armored samurai deep crimson armor kuwagata horns", "unarmored ronin dark robes scarred face", "unarmored ronin wet hair stoic expression", "silhouette warrior kasa hat against sky"],
            "backgrounds": ["dark misty plains bokeh campfire lights", "golden amber wheat field explosive sunset backlight", "heavy rain storm dark storm clouds puddle reflections", "field of deep crimson poppies grey sky", "snowfall white mountain peaks cold palette", "burning battlefield orange fire embers smoke", "explosive gold orange sunset silhouette sky"],
            "angles":      ["extreme close-up oni mask fills entire frame", "medium portrait chest to head low angle", "full body low angle dramatic sky behind", "from behind facing vast landscape", "profile side view strong rim light"],
        },
    }
    style_key = style.lower()
    variety = _VARIETY.get(style_key, _VARIETY["hokan"])

    history = _load_history()
    warriors    = variety["warriors"]
    backgrounds = variety["backgrounds"]
    angles      = variety["angles"]

    w = _pick_diverse(warriors, "warrior", history)
    bg = _pick_diverse(backgrounds, "background", history)
    ang = _pick_diverse(angles, "angle", history)
    history.append({"warrior": w, "background": bg, "angle": ang})
    _save_history(history)

    user_msg = (
        f"Generate one unique scene with these specific choices:\n"
        f"- Warrior: {w}\n- Background: {bg}\n- Camera angle: {ang}\n\n"
        f"Return ONLY the JSON object."
    )
    full_prompt = f"{master}\n\n{user_msg}"

    claude_cli = _find_claude_cli()
    if not claude_cli:
        _diag_log("CLI not found via _find_claude_cli")
        print("[Claude] CLI not found", flush=True)
        return None
    _diag_log(f"CLI path: {claude_cli}")

    try:
        prompt_with_instruction = full_prompt + "\n\nReturn ONLY the JSON object, nothing else."
        print(f"[Claude] Sending via -p flag ({len(prompt_with_instruction)} chars)", flush=True)
        _diag_log(f"subprocess.run start, prompt_len={len(prompt_with_instruction)}, style={style}")

        result = subprocess.run(
            [claude_cli, "-p", prompt_with_instruction, "--output-format", "text"],
            capture_output=True, text=True, encoding='utf-8', timeout=120,
        )

        print(f"[Claude] rc={result.returncode} stdout={result.stdout[:500]!r}", flush=True)
        _diag_log(
            f"subprocess.run done rc={result.returncode} "
            f"stdout_len={len(result.stdout or '')} stderr_len={len(result.stderr or '')}"
        )
        if result.returncode != 0 or not (result.stdout or "").strip():
            _diag_log(f"FAIL stdout[:500]={result.stdout[:500]!r}")
            _diag_log(f"FAIL stderr[:1500]={result.stderr[:1500]!r}")
        if result.returncode == 0 and result.stdout.strip():
            import re
            m = re.search(r'\{.*\}', result.stdout.strip(), re.DOTALL)
            if m:
                try:
                    return json.loads(m.group())
                except Exception as je:
                    _diag_log(f"JSON parse fail: {je}; raw[:500]={m.group()[:500]!r}")
                    print(f"[Claude] JSON parse error: {je}", flush=True)
                    return None
            _diag_log(f"No JSON regex match in stdout[:500]={result.stdout[:500]!r}")
            print(f"[Claude] No JSON found", flush=True)
        else:
            print(f"[Claude] stderr={result.stderr[:300]!r}", flush=True)
    except subprocess.TimeoutExpired as e:
        _diag_log(f"subprocess timeout after {e.timeout}s")
        print(f"[Claude] Timeout: {e}", flush=True)
    except Exception as e:
        _diag_log(f"Exception: {type(e).__name__}: {e}")
        print(f"[Claude] Error: {e}", flush=True)

    return None


def _diag_log(msg: str) -> None:
    """Append diagnostic line to python/prompt_diag.log (для дебагу running backend)."""
    try:
        path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "prompt_diag.log")
        with open(path, "a", encoding="utf-8") as f:
            f.write(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] {msg}\n")
    except Exception:
        pass


def _generate_prompt_json_with_gemini_UNUSED(style: str, custom_prompt: str, api_key: str) -> dict | None:
    """Генерує повний JSON промпт через Gemini використовуючи повний master prompt."""
    master = _load_master_prompt()
    master_str = json.dumps(master, ensure_ascii=False) if master else ""

    prompt_text = (
        "You are an expert AI image prompt engineer for mushinjournal samurai Instagram account.\n"
        "Below is the complete master style guide in JSON format.\n"
        "Follow it EXACTLY: use the correct frequency weights for character type, camera angle, and background.\n"
        "Vary the details every generation: armor color, specific weather details, lighting direction, battle damage.\n\n"
        f"MASTER STYLE GUIDE:\n{master_str}\n\n"
    )
    if custom_prompt:
        prompt_text += f"Additional context to incorporate: {custom_prompt}\n\n"
    prompt_text += (
        "Generate ONE unique image prompt following the style guide.\n"
        "Return ONLY a JSON object with these exact fields:\n"
        "{\n"
        '  "id": 1,\n'
        '  "warrior": "samurai | ronin | silhouette",\n'
        '  "shot": "short description of the shot type, e.g. oni mask close-up",\n'
        '  "atmosphere": "weather and atmosphere, e.g. rain + steam",\n'
        '  "palette": "specific color palette, e.g. deep prussian navy, matte obsidian black",\n'
        '  "prompt": "full hyper-detailed prompt in English, 4-6 sentences with all quality tags"\n'
        "}"
    )

    for attempt in range(3):
        try:
            resp = requests.post(
                f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}",
                headers={"Content-Type": "application/json"},
                json={"contents": [{"parts": [{"text": prompt_text}]}],
                      "generationConfig": {"maxOutputTokens": 2048, "temperature": 1.0,
                                           "response_mime_type": "application/json"}},
                timeout=30,
            )
            if resp.status_code == 200:
                text = resp.json()["candidates"][0]["content"]["parts"][0]["text"].strip()
                # response_mime_type=json повертає чистий JSON без markdown
                try:
                    return json.loads(text)
                except Exception:
                    import re
                    m = re.search(r'\{.*\}', text, re.DOTALL)
                    if m:
                        try:
                            return json.loads(m.group())
                        except Exception:
                            continue
        except Exception:
            continue
    return None


def _generate_prompt_with_gemini_UNUSED(style: str, custom_prompt: str, api_key: str) -> str | None:
    """Генерує промпт для зображення через Google Gemini API."""
    master = _load_master_prompt()

    if master:
        master_str = json.dumps(master, ensure_ascii=False)
        prompt_text = (
            "You are an expert AI image prompt engineer.\n"
            "You have a master style guide (JSON) describing the exact visual style of a successful Instagram account.\n"
            "Generate ONE unique image generation prompt strictly following this style guide.\n"
            "Choose character type, camera angle, and background according to the frequency weights in the guide.\n"
            "Respond ONLY with a JSON object in this exact format, no extra text:\n"
            "{\n"
            '  "prompt": "RAW photo, Canon EOS R5, 85mm f/1.4... (full detailed prompt in English)",\n'
            '  "negative_prompt": "illustration, anime, CGI, 3D render, painting, cartoon, bright colors, smiling",\n'
            '  "character": "armored_samurai | unarmored_ronin | silhouette",\n'
            '  "background": "rain_fog | golden_fields | snow | crimson_flowers | fire | sunset",\n'
            '  "camera": "extreme_closeup | medium_portrait | full_body | from_behind | profile"\n'
            "}\n\n"
            f"Master style guide:\n{master_str}\n\nGenerate a unique prompt now."
        )
        if custom_prompt:
            prompt_text += f"\n\nAdditional user context to incorporate: {custom_prompt}"
    else:
        prompt_text = (
            "You are an expert AI image prompt engineer.\n"
            f"Create a photorealistic image prompt for a {style} warrior, 9:16 vertical, cinematic.\n"
            "Respond ONLY with JSON:\n"
            "{\n"
            '  "prompt": "...",\n'
            '  "negative_prompt": "illustration, anime, CGI, 3D render, painting",\n'
            '  "character": "warrior",\n'
            '  "background": "dramatic",\n'
            '  "camera": "medium_portrait"\n'
            "}"
        )
        if custom_prompt:
            prompt_text += f"\n\nContext: {custom_prompt}"

    try:
        resp = requests.post(
            f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}",
            headers={"Content-Type": "application/json"},
            json={
                "contents": [{"parts": [{"text": prompt_text}]}],
                "generationConfig": {"maxOutputTokens": 800, "temperature": 1.0},
            },
            timeout=30,
        )
        if resp.status_code == 200:
            data = resp.json()
            text = data["candidates"][0]["content"]["parts"][0]["text"].strip()
            # Витягуємо JSON з відповіді (може бути в ```json блоці)
            import re
            m = re.search(r'\{.*\}', text, re.DOTALL)
            if m:
                try:
                    parsed = json.loads(m.group())
                    return parsed.get("prompt", text)
                except Exception:
                    pass
            return text
        return None
    except Exception:
        return None




# ===== IMAGE GENERATION =====

def generate_image(prompt: str, style: str, provider: str, api_key: str, variant_index: int = -1, claude_api_key: str = "", gemini_api_key: str = "") -> dict:
    # If prompt already provided from UI (generated by Claude) — use it directly
    full_prompt = prompt if prompt else _build_image_prompt(style, prompt, variant_index, claude_api_key, gemini_api_key)
    try:
        if provider == "stability":
            return _stability_image(full_prompt, api_key)
        elif provider == "openai":
            return _openai_image(full_prompt, api_key)
        elif provider == "replicate":
            return _replicate_image(full_prompt, api_key)
        elif provider == "google":
            return _google_imagen(full_prompt, api_key)
        else:
            return {"ok": False, "error": f"Невідомий провайдер: {provider}"}
    except Exception as e:
        return {"ok": False, "error": f"{type(e).__name__}: {str(e)}"}


def _stability_image(prompt: str, api_key: str) -> dict:
    """Stability AI — Stable Image Core / SDXL"""
    url = "https://api.stability.ai/v2beta/stable-image/generate/core"
    resp = requests.post(
        url,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Accept": "image/*",
        },
        files={"none": ""},
        data={
            "prompt": prompt,
            "output_format": "png",
            "aspect_ratio": "9:16",
        },
        timeout=60,
    )
    if resp.status_code == 200:
        path = os.path.join(OUTPUT_DIR, f"img_{int(time.time())}.png")
        with open(path, "wb") as f:
            f.write(resp.content)
        return {"ok": True, "path": path}
    else:
        try:
            err = resp.json()
            msg = err.get("message", err.get("name", resp.text[:200]))
        except Exception:
            msg = resp.text[:200]
        return {"ok": False, "error": f"Stability API {resp.status_code}: {msg}"}


def _openai_image(prompt: str, api_key: str) -> dict:
    """OpenAI DALL-E 3"""
    resp = requests.post(
        "https://api.openai.com/v1/images/generations",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": "dall-e-3",
            "prompt": prompt,
            "n": 1,
            "size": "1024x1792",
            "response_format": "b64_json",
        },
        timeout=60,
    )
    if resp.status_code == 200:
        data = resp.json()
        b64 = data["data"][0]["b64_json"]
        path = os.path.join(OUTPUT_DIR, f"img_{int(time.time())}.png")
        with open(path, "wb") as f:
            f.write(base64.b64decode(b64))
        return {"ok": True, "path": path}
    else:
        try:
            err = resp.json()
            msg = err.get("error", {}).get("message", resp.text[:200])
        except Exception:
            msg = resp.text[:200]
        return {"ok": False, "error": f"OpenAI API {resp.status_code}: {msg}"}


def _replicate_image(prompt: str, api_key: str) -> dict:
    """Replicate — Flux Schnell"""
    # Create prediction
    resp = requests.post(
        "https://api.replicate.com/v1/models/black-forest-labs/flux-schnell/predictions",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "input": {
                "prompt": prompt,
                "aspect_ratio": "9:16",
                "output_format": "png",
            }
        },
        timeout=30,
    )
    if resp.status_code not in (200, 201):
        return {"ok": False, "error": f"Replicate API {resp.status_code}: {resp.text[:200]}"}

    prediction = resp.json()
    poll_url = prediction.get("urls", {}).get("get", f"https://api.replicate.com/v1/predictions/{prediction['id']}")

    # Poll for result
    for _ in range(60):
        time.sleep(3)
        poll = requests.get(poll_url, headers={"Authorization": f"Bearer {api_key}"}, timeout=15)
        data = poll.json()
        status = data.get("status")
        if status == "succeeded":
            output = data.get("output")
            image_url = output[0] if isinstance(output, list) else output
            img_resp = requests.get(image_url, timeout=30)
            path = os.path.join(OUTPUT_DIR, f"img_{int(time.time())}.png")
            with open(path, "wb") as f:
                f.write(img_resp.content)
            return {"ok": True, "path": path}
        elif status == "failed":
            return {"ok": False, "error": f"Replicate failed: {data.get('error', 'unknown')}"}

    return {"ok": False, "error": "Replicate timeout"}


def _google_imagen(prompt: str, api_key: str) -> dict:
    """Google Imagen 4 via AI Studio API key"""

    def _try_imagen4(model: str) -> dict | None:
        """Imagen 4 — predict endpoint"""
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:predict?key={api_key}"
        resp = requests.post(url, headers={"Content-Type": "application/json"}, json={
            "instances": [{"prompt": prompt}],
            "parameters": {"sampleCount": 1, "aspectRatio": "9:16"},
        }, timeout=120)
        if resp.status_code == 200:
            predictions = resp.json().get("predictions", [])
            if predictions:
                b64 = predictions[0].get("bytesBase64Encoded", "")
                if b64:
                    path = os.path.join(OUTPUT_DIR, f"img_{int(time.time())}.png")
                    with open(path, "wb") as f:
                        f.write(base64.b64decode(b64))
                    return {"ok": True, "path": path}
        return None

    def _try_gemini_image(model: str) -> dict | None:
        """Gemini image models — generateContent endpoint"""
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
        resp = requests.post(url, headers={"Content-Type": "application/json"}, json={
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"responseModalities": ["IMAGE"]},
        }, timeout=120)
        if resp.status_code == 200:
            try:
                parts = resp.json()["candidates"][0]["content"]["parts"]
                for part in parts:
                    if "inlineData" in part:
                        b64 = part["inlineData"]["data"]
                        path = os.path.join(OUTPUT_DIR, f"img_{int(time.time())}.png")
                        with open(path, "wb") as f:
                            f.write(base64.b64decode(b64))
                        return {"ok": True, "path": path}
            except (KeyError, IndexError):
                pass
        return None

    # Спробуємо моделі по черзі від найкращої
    for attempt in [
        lambda: _try_imagen4("imagen-4.0-generate-001"),
        lambda: _try_gemini_image("gemini-2.5-flash-image"),
        lambda: _try_gemini_image("gemini-3-pro-image-preview"),
        lambda: _try_gemini_image("gemini-3.1-flash-image-preview"),
    ]:
        result = attempt()
        if result:
            return result

    return {"ok": False, "error": "Google Imagen: жодна модель не повернула зображення. Перевірте API ключ."}


# ===== VIDEO GENERATION =====

def generate_video(image_path: str, prompt: str, provider: str, api_key: str) -> dict:
    try:
        if provider == "kling":
            return _kling_video(image_path, prompt, api_key)
        elif provider == "runway":
            return _runway_video(image_path, prompt, api_key)
        elif provider == "luma":
            return _luma_video(image_path, prompt, api_key)
        elif provider == "veo":
            return _veo_video(image_path, prompt, api_key)
        elif provider == "nhungoc_veo3":
            return _nhungoc_veo3_video(image_path, prompt, api_key)
        else:
            return {"ok": False, "error": f"Невідомий провайдер відео: {provider}"}
    except Exception as e:
        return {"ok": False, "error": f"{type(e).__name__}: {str(e)}"}


def _image_to_base64(path: str) -> str:
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode()


def _kling_jwt(access_key: str, secret_key: str) -> str:
    """Generate JWT token for Kling AI API."""
    import struct

    # Header
    header = base64.urlsafe_b64encode(json.dumps({"alg": "HS256", "typ": "JWT"}).encode()).rstrip(b"=")

    # Payload
    now = int(time.time())
    payload_data = {
        "iss": access_key,
        "exp": now + 1800,
        "nbf": now - 5,
        "iat": now,
    }
    payload = base64.urlsafe_b64encode(json.dumps(payload_data).encode()).rstrip(b"=")

    # Signature
    signing_input = header + b"." + payload
    signature = base64.urlsafe_b64encode(
        hmac.new(secret_key.encode(), signing_input, hashlib.sha256).digest()
    ).rstrip(b"=")

    return (signing_input + b"." + signature).decode()


def _kling_video(image_path: str, prompt: str, api_key: str) -> dict:
    """Kling AI — image-to-video via official API.
    api_key format: 'access_key:secret_key'
    """
    if ":" not in api_key:
        return {"ok": False, "error": "Kling API key має бути у форматі 'access_key:secret_key'"}

    access_key, secret_key = api_key.split(":", 1)
    token = _kling_jwt(access_key, secret_key)

    img_b64 = _image_to_base64(image_path)

    # Create task
    resp = requests.post(
        "https://api.klingai.com/v1/videos/image2video",
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        json={
            "model_name": "kling-v1",
            "mode": "std",
            "duration": "5",
            "image": img_b64,
            "prompt": prompt or "Slow cinematic camera movement, dramatic lighting",
        },
        timeout=30,
    )

    if resp.status_code not in (200, 201):
        return {"ok": False, "error": f"Kling API {resp.status_code}: {resp.text[:300]}"}

    data = resp.json()
    task_id = data.get("data", {}).get("task_id")
    if not task_id:
        return {"ok": False, "error": f"Kling: no task_id in response: {json.dumps(data)[:300]}"}

    # Poll for result
    for _ in range(120):  # ~10 min max
        time.sleep(5)
        token = _kling_jwt(access_key, secret_key)  # refresh token
        poll = requests.get(
            f"https://api.klingai.com/v1/videos/image2video/{task_id}",
            headers={"Authorization": f"Bearer {token}"},
            timeout=15,
        )
        result = poll.json()
        task_status = result.get("data", {}).get("task_status")

        if task_status == "succeed":
            videos = result.get("data", {}).get("task_result", {}).get("videos", [])
            if videos:
                video_url = videos[0].get("url")
                vid_resp = requests.get(video_url, timeout=60)
                path = os.path.join(OUTPUT_DIR, f"vid_{int(time.time())}.mp4")
                with open(path, "wb") as f:
                    f.write(vid_resp.content)
                return {"ok": True, "path": path}
            return {"ok": False, "error": "Kling: відео не знайдено у відповіді"}
        elif task_status == "failed":
            msg = result.get("data", {}).get("task_status_msg", "unknown error")
            return {"ok": False, "error": f"Kling failed: {msg}"}

    return {"ok": False, "error": "Kling timeout (10 хвилин)"}


def _runway_video(image_path: str, prompt: str, api_key: str) -> dict:
    """Runway ML Gen-3 Alpha — image-to-video."""
    img_b64 = _image_to_base64(image_path)

    resp = requests.post(
        "https://api.dev.runwayml.com/v1/image_to_video",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "X-Runway-Version": "2024-11-06",
        },
        json={
            "model": "gen3a_turbo",
            "promptImage": f"data:image/png;base64,{img_b64}",
            "promptText": prompt or "Slow cinematic camera movement, dramatic lighting",
            "duration": 5,
            "ratio": "768:1344",
        },
        timeout=30,
    )

    if resp.status_code not in (200, 201):
        return {"ok": False, "error": f"Runway API {resp.status_code}: {resp.text[:300]}"}

    task_id = resp.json().get("id")

    # Poll
    for _ in range(120):
        time.sleep(5)
        poll = requests.get(
            f"https://api.dev.runwayml.com/v1/tasks/{task_id}",
            headers={"Authorization": f"Bearer {api_key}"},
            timeout=15,
        )
        result = poll.json()
        status = result.get("status")

        if status == "SUCCEEDED":
            video_url = result.get("output", [None])[0]
            if video_url:
                vid_resp = requests.get(video_url, timeout=60)
                path = os.path.join(OUTPUT_DIR, f"vid_{int(time.time())}.mp4")
                with open(path, "wb") as f:
                    f.write(vid_resp.content)
                return {"ok": True, "path": path}
            return {"ok": False, "error": "Runway: відео не знайдено"}
        elif status == "FAILED":
            return {"ok": False, "error": f"Runway failed: {result.get('failure', 'unknown')}"}

    return {"ok": False, "error": "Runway timeout"}


def _luma_video(image_path: str, prompt: str, api_key: str) -> dict:
    """Luma Dream Machine — image-to-video."""
    img_b64 = _image_to_base64(image_path)

    resp = requests.post(
        "https://api.lumalabs.ai/dream-machine/v1/generations",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "prompt": prompt or "Slow cinematic camera movement, dramatic lighting",
            "keyframes": {
                "frame0": {
                    "type": "image",
                    "url": f"data:image/png;base64,{img_b64}",
                }
            },
            "aspect_ratio": "9:16",
        },
        timeout=30,
    )

    if resp.status_code not in (200, 201):
        return {"ok": False, "error": f"Luma API {resp.status_code}: {resp.text[:300]}"}

    gen_id = resp.json().get("id")

    # Poll
    for _ in range(120):
        time.sleep(5)
        poll = requests.get(
            f"https://api.lumalabs.ai/dream-machine/v1/generations/{gen_id}",
            headers={"Authorization": f"Bearer {api_key}"},
            timeout=15,
        )
        result = poll.json()
        state = result.get("state")

        if state == "completed":
            video_url = result.get("assets", {}).get("video")
            if video_url:
                vid_resp = requests.get(video_url, timeout=60)
                path = os.path.join(OUTPUT_DIR, f"vid_{int(time.time())}.mp4")
                with open(path, "wb") as f:
                    f.write(vid_resp.content)
                return {"ok": True, "path": path}
            return {"ok": False, "error": "Luma: відео не знайдено"}
        elif state == "failed":
            return {"ok": False, "error": f"Luma failed: {result.get('failure_reason', 'unknown')}"}

    return {"ok": False, "error": "Luma timeout"}


def _veo_video(image_path: str, prompt: str, api_key: str) -> dict:
    """Google Veo 3 — image-to-video via AI Studio API key."""
    img_b64 = _image_to_base64(image_path)

    # Додаємо дисклеймер щоб уникнути фільтру відомих людей
    disclaimer = "Fictional warrior character. Not based on any real person, living or dead."
    safe_prompt = f"{prompt} {disclaimer}" if prompt else disclaimer

    # Спробуємо Veo 3 (найкраща), якщо 403/404 — fallback на Veo 2
    for model in ["veo-3.0-fast-generate-001", "veo-2.0-generate-001"]:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:predictLongRunning?key={api_key}"
        resp = requests.post(
            url,
            headers={"Content-Type": "application/json"},
            json={
                "instances": [{
                    "prompt": safe_prompt or "Epic cinematic slow motion, dramatic camera push-in. Fictional character, not a real person.",
                    "image": {"bytesBase64Encoded": img_b64, "mimeType": "image/png"},
                }],
                "parameters": {
                    "aspectRatio": "9:16",
                    "durationSeconds": 8,
                    "sampleCount": 1,
                },
            },
            timeout=60,
        )

        if resp.status_code in (403, 404):
            continue  # спробуємо наступну модель

        if resp.status_code != 200:
            try:
                msg = resp.json().get("error", {}).get("message", resp.text[:300])
            except Exception:
                msg = resp.text[:300]
            if "PROMINENT_PEOPLE_FILTER" in msg:
                return {"ok": False, "error": "Veo: промт схожий на реальну відому людину. Перегенеруй промт або зміни опис персонажа."}
            return {"ok": False, "error": f"Veo {resp.status_code}: {msg}"}

        operation_name = resp.json().get("name")
        if not operation_name:
            return {"ok": False, "error": "Veo: не отримано operation name"}

        # Polling long-running operation
        poll_url = f"https://generativelanguage.googleapis.com/v1beta/{operation_name}?key={api_key}"
        for _ in range(120):  # max 10 хвилин
            time.sleep(5)
            poll = requests.get(poll_url, timeout=15)
            if poll.status_code != 200:
                continue
            result = poll.json()
            if not result.get("done"):
                continue

            # Перевіряємо помилку в операції
            if result.get("error"):
                err_msg = result["error"].get("message", str(result["error"]))
                if "PROMINENT_PEOPLE_FILTER" in err_msg:
                    return {"ok": False, "error": "Veo: промт схожий на реальну відому людину. Перегенеруй промт або зміни опис персонажа."}
                return {"ok": False, "error": f"Veo: {err_msg}"}

            # Готово — розбираємо структуру відповіді
            response_data = result.get("response", result)
            # Перевіряємо operations[] на помилки (Veo 3 повертає так)
            ops = response_data.get("operations", [])
            if ops:
                for op in ops:
                    op_err = op.get("error", {})
                    if op_err:
                        op_msg = op_err.get("message", str(op_err))
                        if "PROMINENT_PEOPLE_FILTER" in op_msg:
                            return {"ok": False, "error": "Veo: промт схожий на реальну відому людину. Перегенеруй промт або зміни опис персонажа."}
                        return {"ok": False, "error": f"Veo: {op_msg}"}
            # Veo повертає response.generateVideoResponse
            if "generateVideoResponse" in response_data:
                response_data = response_data["generateVideoResponse"]
            # Спробуємо різні структури відповіді
            try:
                # Варіант 1: response.predictions[0].bytesBase64Encoded
                predictions = response_data.get("predictions", [])
                if predictions:
                    video_b64 = predictions[0].get("bytesBase64Encoded", "")
                    if video_b64:
                        path = os.path.join(OUTPUT_DIR, f"vid_{int(time.time())}.mp4")
                        with open(path, "wb") as f:
                            f.write(base64.b64decode(video_b64))
                        return {"ok": True, "path": path}
                    video_uri = predictions[0].get("videoUri", "")
                    if video_uri:
                        vid_resp = requests.get(video_uri, timeout=60)
                        path = os.path.join(OUTPUT_DIR, f"vid_{int(time.time())}.mp4")
                        with open(path, "wb") as f:
                            f.write(vid_resp.content)
                        return {"ok": True, "path": path}

                # Варіант 2: generatedSamples[0].video
                samples = response_data.get("generatedSamples", [])
                if samples:
                    video_obj = samples[0].get("video", {})
                    video_b64 = video_obj.get("bytesBase64Encoded", "")
                    if video_b64:
                        path = os.path.join(OUTPUT_DIR, f"vid_{int(time.time())}.mp4")
                        with open(path, "wb") as f:
                            f.write(base64.b64decode(video_b64))
                        return {"ok": True, "path": path}
                    video_uri = video_obj.get("uri", video_obj.get("videoUri", ""))
                    if video_uri:
                        # Додаємо API ключ для завантаження з Google Files API
                        sep = "&" if "?" in video_uri else "?"
                        download_url = f"{video_uri}{sep}key={api_key}"
                        vid_resp = requests.get(download_url, timeout=120)
                        path = os.path.join(OUTPUT_DIR, f"vid_{int(time.time())}.mp4")
                        with open(path, "wb") as f:
                            f.write(vid_resp.content)
                        return {"ok": True, "path": path}

                # Нічого не знайдено — повертаємо структуру для діагностики
                keys = list(response_data.keys())
                return {"ok": False, "error": f"Veo: невідома структура відповіді. Ключі: {keys}"}

            except Exception as e:
                return {"ok": False, "error": f"Veo: {e}. Response keys: {list(response_data.keys())}"}

        return {"ok": False, "error": "Veo timeout (10 хвилин)"}

    return {"ok": False, "error": "Veo: немає доступних моделей для цього API ключа"}


# ===== FFMPEG COMPOSE =====

def _find_font() -> str:
    """Find a usable font file on Windows."""
    candidates = [
        r"C:\Windows\Fonts\arial.ttf",
        r"C:\Windows\Fonts\Arial.ttf",
        r"C:\Windows\Fonts\calibri.ttf",
        r"C:\Windows\Fonts\segoeui.ttf",
        r"C:\Windows\Fonts\tahoma.ttf",
        r"C:\Windows\Fonts\verdana.ttf",
    ]
    for p in candidates:
        if os.path.isfile(p):
            return p.replace("\\", "/")
    return ""


def _find_cjk_font() -> str:
    """Find a font that supports CJK (kanji) characters."""
    candidates = [
        r"C:\Windows\Fonts\YuGothL.ttc",
        r"C:\Windows\Fonts\YuGothR.ttc",
        r"C:\Windows\Fonts\YuGothM.ttc",
        r"C:\Windows\Fonts\msgothic.ttc",
        r"C:\Windows\Fonts\RODE Noto Sans CJK SC R.otf",
        r"C:\Windows\Fonts\meiryo.ttc",
        r"C:\Windows\Fonts\malgun.ttf",
    ]
    for p in candidates:
        if os.path.isfile(p):
            return p.replace("\\", "/")
    return _find_font()


def _find_ffmpeg() -> str:
    """Find ffmpeg binary."""
    for cmd in ["ffmpeg", "ffmpeg.exe"]:
        try:
            subprocess.run([cmd, "-version"], capture_output=True, timeout=5)
            return cmd
        except Exception:
            continue
    # Common Windows paths
    for p in [
        os.path.expanduser(r"~\AppData\Local\Microsoft\WinGet\Links\ffmpeg.exe"),
        os.path.expanduser(r"~\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-7.1-full_build\bin\ffmpeg.exe"),
        r"C:\ProgramData\chocolatey\bin\ffmpeg.exe",
        r"C:\Program Files\FFmpeg\bin\ffmpeg.exe",
        r"C:\ffmpeg\bin\ffmpeg.exe",
        os.path.expanduser(r"~\scoop\shims\ffmpeg.exe"),
    ]:
        if os.path.isfile(p):
            return p
    return "ffmpeg"


def _get_video_duration(video_path: str) -> float:
    """Повертає тривалість відео у секундах через ffprobe. 0.0 якщо не вдалось."""
    if not video_path or not os.path.isfile(video_path):
        return 0.0
    ffmpeg = _find_ffmpeg()
    # ffprobe зазвичай поряд з ffmpeg
    ffprobe = ffmpeg.replace("ffmpeg.exe", "ffprobe.exe").replace("ffmpeg", "ffprobe")
    if ffprobe == ffmpeg:
        ffprobe = "ffprobe"
    try:
        result = subprocess.run(
            [ffprobe, "-v", "error", "-show_entries", "format=duration",
             "-of", "default=noprint_wrappers=1:nokey=1", video_path],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0 and result.stdout.strip():
            return float(result.stdout.strip())
    except Exception:
        pass
    return 0.0


# ===== HARDWARE ACCELERATION DETECTION =====

_HW_ENCODER_CACHE = None

def _detect_hw_encoder() -> str:
    """Визначає найкращий доступний hardware encoder.

    Returns: 'qsv' | 'nvenc' | 'amf' | 'cpu'
    Кеш — детект робиться 1 раз.
    """
    global _HW_ENCODER_CACHE
    if _HW_ENCODER_CACHE is not None:
        return _HW_ENCODER_CACHE

    ffmpeg = _find_ffmpeg()
    # Тест 1: Intel QSV
    try:
        r = subprocess.run([
            ffmpeg, "-y", "-f", "lavfi", "-i", "testsrc=duration=0.2:size=320x240:rate=10",
            "-c:v", "h264_qsv", "-f", "null", "-",
        ], capture_output=True, text=True, timeout=10)
        if r.returncode == 0:
            _HW_ENCODER_CACHE = "qsv"
            print("[HW] Using Intel QSV encoder", flush=True)
            return "qsv"
    except Exception:
        pass

    # Тест 2: NVIDIA NVENC
    try:
        r = subprocess.run([
            ffmpeg, "-y", "-f", "lavfi", "-i", "testsrc=duration=0.2:size=320x240:rate=10",
            "-c:v", "h264_nvenc", "-f", "null", "-",
        ], capture_output=True, text=True, timeout=10)
        if r.returncode == 0:
            _HW_ENCODER_CACHE = "nvenc"
            print("[HW] Using NVIDIA NVENC encoder", flush=True)
            return "nvenc"
    except Exception:
        pass

    # Тест 3: AMD AMF
    try:
        r = subprocess.run([
            ffmpeg, "-y", "-f", "lavfi", "-i", "testsrc=duration=0.2:size=320x240:rate=10",
            "-c:v", "h264_amf", "-f", "null", "-",
        ], capture_output=True, text=True, timeout=10)
        if r.returncode == 0:
            _HW_ENCODER_CACHE = "amf"
            print("[HW] Using AMD AMF encoder", flush=True)
            return "amf"
    except Exception:
        pass

    _HW_ENCODER_CACHE = "cpu"
    print("[HW] No HW encoder detected, using libx264 CPU", flush=True)
    return "cpu"


def _video_encoder_args(crf: int = 20) -> list:
    """Повертає ffmpeg args для кодування відео — HW якщо є, інакше CPU.

    crf: quality 0-51 (18-23 типово). Для HW енкодерів мапиться на bitrate/qp.
    """
    enc = _detect_hw_encoder()
    if enc == "qsv":
        # Intel Quick Sync — preset veryfast, global_quality мапиться з CRF
        return ["-c:v", "h264_qsv", "-preset", "veryfast", "-global_quality", str(crf)]
    if enc == "nvenc":
        # NVIDIA NVENC — preset p4 (balanced), CQ mode
        return ["-c:v", "h264_nvenc", "-preset", "p4", "-cq", str(crf)]
    if enc == "amf":
        return ["-c:v", "h264_amf", "-quality", "speed", "-rc", "cqp", "-qp_i", str(crf), "-qp_p", str(crf)]
    # CPU fallback — ultrafast замість fast (сильно швидше, трохи більший файл)
    return ["-c:v", "libx264", "-crf", str(crf), "-preset", "ultrafast"]


def _subprocess_low_priority_flags() -> dict:
    """Returns kwargs для subprocess.run щоб запустити з низьким пріоритетом (Windows).

    Щоб не палити ноут навіть на CPU режимі.
    """
    import sys as _sys
    if _sys.platform == "win32":
        # 0x00004000 = BELOW_NORMAL_PRIORITY_CLASS
        return {"creationflags": 0x00004000}
    return {}


def _remove_veo_watermark(video_path: str) -> str:
    """Remove Veo watermark using OpenCV inpaint on each frame.
    Detects bright 'Veo' text in bottom-right corner and fills with surrounding texture."""
    try:
        import cv2
        import numpy as np
    except ImportError:
        # Fallback to crop if OpenCV not available
        return _remove_veo_watermark_crop(video_path)

    ffmpeg = _find_ffmpeg()
    clean_path = video_path.replace(".mp4", "_clean.mp4")

    try:
        # Extract frames
        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            return video_path

        fps = cap.get(cv2.CAP_PROP_FPS) or 24
        w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
        temp_raw = video_path.replace(".mp4", "_raw.mp4")
        writer = cv2.VideoWriter(temp_raw, fourcc, fps, (w, h))

        # Fixed mask for Veo watermark: bottom-right corner, ~155x85px
        watermark_mask = np.zeros((h, w), dtype=np.uint8)
        watermark_mask[h-85:h, w-155:w] = 255

        frame_count = 0
        while True:
            ret, frame = cap.read()
            if not ret:
                break

            clean_frame = cv2.inpaint(frame, watermark_mask, 12, cv2.INPAINT_TELEA)
            writer.write(clean_frame)
            frame_count += 1

        cap.release()
        writer.release()

        if frame_count == 0:
            return video_path

        # Mux with original audio using ffmpeg
        result = subprocess.run([
            ffmpeg, "-y",
            "-i", temp_raw,
            "-i", video_path,
            "-map", "0:v", "-map", "1:a?",
        ] + _video_encoder_args(crf=20) + [
            "-c:a", "copy",
            "-shortest",
            clean_path,
        ], capture_output=True, text=True, timeout=120, **_subprocess_low_priority_flags())

        try:
            os.remove(temp_raw)
        except:
            pass

        if os.path.isfile(clean_path) and os.path.getsize(clean_path) > 1000:
            os.remove(video_path)
            os.rename(clean_path, video_path)
            return video_path

    except Exception:
        pass

    return video_path


def _find_rife() -> str:
    """Знаходить rife-ncnn-vulkan.exe (AI frame interpolation для CapCut-якості slow mo)."""
    local = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "tools", "rife-ncnn-vulkan-20221029-windows", "rife-ncnn-vulkan.exe",
    )
    if os.path.isfile(local):
        return local
    return ""


def _apply_slow_motion_rife(video_path: str, factor: float = 0.7, model: str = "rife-v4.6") -> str:
    """AI-інтерпольоване заповільнення через RIFE (якість як у CapCut).

    Працює через Vulkan (Intel Xe або NVIDIA). Повільніше за blend, але якість суттєво краща.
    """
    rife = _find_rife()
    if not rife:
        print("[rife] не знайдено, fallback на blend", flush=True)
        return _apply_slow_motion_blend(video_path, factor)

    ffmpeg = _find_ffmpeg()
    rife_dir = os.path.dirname(rife)
    model_path = os.path.join(rife_dir, model)
    if not os.path.isdir(model_path):
        print(f"[rife] model {model} not found, using rife-v4.6", flush=True)
        model_path = os.path.join(rife_dir, "rife-v4.6")

    import tempfile as _tmp
    import shutil as _sh
    work = _tmp.mkdtemp(prefix="rife_")
    frames_in = os.path.join(work, "in")
    frames_out = os.path.join(work, "out")
    os.makedirs(frames_in)
    os.makedirs(frames_out)
    slow_path = video_path.replace(".mp4", "_rife.mp4")

    try:
        # 1. Витягуємо кадри з вхідного відео
        subprocess.run([
            ffmpeg, "-y", "-i", video_path,
            "-qscale:v", "2",  # висока якість PNG
            os.path.join(frames_in, "%08d.png"),
        ], capture_output=True, text=True, timeout=180, **_subprocess_low_priority_flags())

        frame_count = len([f for f in os.listdir(frames_in) if f.endswith(".png")])
        if frame_count < 2:
            print("[rife] недостатньо кадрів", flush=True)
            return video_path

        # 2. RIFE інтерполяція — target кількість кадрів = frame_count / factor
        # factor=0.7 → target = 1.43 * frame_count
        target_frames = int(round(frame_count / factor))
        print(f"[rife] {frame_count} → {target_frames} кадрів (factor={factor})", flush=True)

        result = subprocess.run([
            rife, "-i", frames_in, "-o", frames_out,
            "-m", model_path,
            "-n", str(target_frames),
            "-g", "0",  # auto-select GPU (0 = перший Vulkan пристрій)
            "-j", "1:2:2",
        ], capture_output=True, text=True, timeout=900, **_subprocess_low_priority_flags())

        if result.returncode != 0:
            print(f"[rife] rc={result.returncode}: {(result.stderr or '')[-400:]}", flush=True)
            return _apply_slow_motion_blend(video_path, factor)

        out_count = len([f for f in os.listdir(frames_out) if f.endswith(".png")])
        if out_count < frame_count:
            print(f"[rife] мало вихідних кадрів: {out_count}", flush=True)
            return _apply_slow_motion_blend(video_path, factor)

        # 3. Збираємо відео назад з QSV encoder
        encode_cmd = [
            ffmpeg, "-y",
            "-framerate", "24",
            "-i", os.path.join(frames_out, "%08d.png"),
            "-an",
        ] + _video_encoder_args(crf=20) + [slow_path]
        result = subprocess.run(encode_cmd, capture_output=True, text=True, timeout=300,
                                **_subprocess_low_priority_flags())
        if result.returncode != 0:
            print(f"[rife encode] rc={result.returncode}: {(result.stderr or '')[-300:]}", flush=True)
            return _apply_slow_motion_blend(video_path, factor)

        if not (os.path.isfile(slow_path) and os.path.getsize(slow_path) > 1000):
            return _apply_slow_motion_blend(video_path, factor)
    except Exception as e:
        print(f"[rife] exception: {e}", flush=True)
        return _apply_slow_motion_blend(video_path, factor)
    finally:
        try:
            _sh.rmtree(work, ignore_errors=True)
        except Exception:
            pass
    # Повертаємо НОВИЙ шлях — оригінал НЕ чіпаємо (щоб History не перезаписалась).
    return slow_path


def _apply_slow_motion_blend(video_path: str, factor: float = 0.7) -> str:
    """Швидке заповільнення через minterpolate blend (CPU-light, помітний blur).

    Легкий режим (швидкий, не вішає ноут):
      - minterpolate blend mode замість mci (5-10x швидше, без motion estimation)
      - fps=48 замість 96 (вдвічі менше інтерпольованих кадрів)
      - QSV/NVENC encoder якщо є
      - Low process priority
    """
    ffmpeg = _find_ffmpeg()
    slow_path = video_path.replace(".mp4", "_slow.mp4")
    pts_mult = round(1.0 / factor, 4)

    cmd = [
        ffmpeg, "-y", "-i", video_path,
        "-filter_complex",
        # blend mode — просто усереднює сусідні кадри (швидко)
        # fps=48 — удвічі менше інтерпольованих кадрів ніж 96
        f"minterpolate=fps=48:mi_mode=blend,setpts={pts_mult}*PTS,fps=24",
        "-an",
    ] + _video_encoder_args(crf=20) + [slow_path]

    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=600,
            **_subprocess_low_priority_flags(),
        )
        if result.returncode != 0:
            print(f"[slow_motion] ffmpeg rc={result.returncode}: {(result.stderr or '')[-400:]}", flush=True)
        # Повертаємо новий шлях щоб НЕ чіпати оригінал
        if os.path.isfile(slow_path) and os.path.getsize(slow_path) > 1000:
            return slow_path
    except Exception as e:
        print(f"[slow_motion] error: {e}", flush=True)
    # Fallback — повертаємо оригінал якщо slow не вдався
    return video_path


def _apply_slow_motion(video_path: str, factor: float = 0.7, mode: str = "blend") -> str:
    """Dispatcher для slow motion.

    mode:
      - 'blend' — швидкий (minterpolate blend), ~20с на 11с відео
      - 'rife'  — AI якість (CapCut-рівень), ~60-120с на 11с відео
      - 'mci'   — motion-compensated (старий), ~60с на 11с відео, 100% CPU
    """
    if mode == "rife":
        return _apply_slow_motion_rife(video_path, factor)
    if mode == "mci":
        return _apply_slow_motion_mci(video_path, factor)
    return _apply_slow_motion_blend(video_path, factor)


def _apply_slow_motion_mci(video_path: str, factor: float = 0.7) -> str:
    """Старий метод — minterpolate mci (motion-compensated). Дуже важкий CPU, якісно."""
    ffmpeg = _find_ffmpeg()
    slow_path = video_path.replace(".mp4", "_mci.mp4")
    pts_mult = round(1.0 / factor, 4)
    cmd = [
        ffmpeg, "-y", "-i", video_path,
        "-filter_complex",
        f"minterpolate=fps=96:mi_mode=mci:mc_mode=aobmc:me_mode=bidir:vsbmc=1,setpts={pts_mult}*PTS,fps=24",
        "-an",
    ] + _video_encoder_args(crf=18) + [slow_path]
    try:
        subprocess.run(cmd, capture_output=True, text=True, timeout=900,
                       **_subprocess_low_priority_flags())
        # Повертаємо новий шлях — оригінал НЕ чіпаємо
        if os.path.isfile(slow_path) and os.path.getsize(slow_path) > 1000:
            return slow_path
    except Exception as e:
        print(f"[slow_motion_mci] error: {e}", flush=True)
    return video_path


def _remove_veo_watermark_crop(video_path: str) -> str:
    """Fallback: remove watermark by cropping bottom-right corner."""
    ffmpeg = _find_ffmpeg()
    clean_path = video_path.replace(".mp4", "_clean.mp4")
    try:
        subprocess.run([
            ffmpeg, "-y", "-i", video_path,
            "-vf", "crop=iw-20:ih-50:0:0,scale=iw+20:ih+50:flags=lanczos",
        ] + _video_encoder_args(crf=20) + [
            "-c:a", "copy",
            clean_path,
        ], capture_output=True, text=True, timeout=120)
        if os.path.isfile(clean_path) and os.path.getsize(clean_path) > 1000:
            os.remove(video_path)
            os.rename(clean_path, video_path)
    except Exception:
        pass
    return video_path


def _nhungoc_veo3_video(image_path: str, prompt: str, api_key: str) -> dict:
    """Generate video via Nhungoc VEO3 WebSocket service.
    Supports both i2v (image-to-video) and t2v (text-to-video).
    Uses i2v when image_path is provided, t2v otherwise.
    """
    import asyncio
    import ssl

    try:
        import websockets
    except ImportError:
        os.system("pip install websockets")
        import websockets

    NHUNGOC_LICENSE = "ELV-333fe11d-1dca8282-6485acf0"
    # Hardware fingerprint цього PC — license прив'язана до нього.
    # Сервер тепер вимагає cpu_id у register payload (повертає "Missing cpu_id" без нього).
    NHUNGOC_CPU_ID = "b014b7d94b33ea5181da4e54ca40730d"
    NHUNGOC_HARDWARE_ID = "487d9020c89526c7ad8e99a02e90de5371bc201545d583220a0e22c413f87ac9"
    NHUNGOC_MAINBOARD = "07E0622_O51E207192"
    NHUNGOC_EMAIL = "maksimyuk00@gmail.com"
    WS_URL = "wss://ws.nhungoc.me/"

    # Always use hardcoded license - ignore api_key from settings
    license_key = NHUNGOC_LICENSE
    aspect = "VIDEO_ASPECT_RATIO_PORTRAIT"
    upscale = True
    duration = 8

    # Determine mode: i2v if image exists, t2v otherwise
    use_i2v = image_path and os.path.isfile(image_path)

    async def _generate():
        ssl_ctx = ssl.create_default_context()
        async with websockets.connect(WS_URL, ssl=ssl_ctx, open_timeout=20,
                                       max_size=50 * 1024 * 1024,
                                       ping_interval=20, ping_timeout=30) as ws:
            # Register з повним hardware fingerprint.
            # Сервер шле ДВА events: спочатку "registered" (pending verification),
            # потім за 1-2с другий "registered" (verified successfully) з can_generate=true.
            # Submit ДО verification дає quota error, тому чекаємо обидва.
            await ws.send(json.dumps({
                "event": "register",
                "data": {
                    "license_key": license_key,
                    "cpu_id": NHUNGOC_CPU_ID,
                    "hardware_id": NHUNGOC_HARDWARE_ID,
                    "mainboard_uuid": NHUNGOC_MAINBOARD,
                    "email": NHUNGOC_EMAIL,
                    "brand": "veo3",
                }
            }))

            verified = False
            for _ in range(3):
                raw = await asyncio.wait_for(ws.recv(), timeout=30)
                msg = json.loads(raw)
                if msg.get("event") != "registered":
                    return {"ok": False, "error": f"Registration failed: {msg}"}
                ver = msg.get("data", {}).get("verification", {})
                if ver.get("success") and ver.get("data", {}).get("can_generate"):
                    verified = True
                    break
                # pending → ще раз приймаємо
                if not ver.get("pending"):
                    # незрозумілий стан — лог і продовжуємо
                    break
            if not verified:
                return {"ok": False, "error": "Verification did not complete (no can_generate=true)"}

            task_id = f"{'i2v' if use_i2v else 't2v'}_{int(time.time())}"

            if use_i2v:
                # Image-to-video: send image + prompt
                img_b64 = _image_to_base64(image_path)
                await ws.send(json.dumps({
                    "event": "submit_image_video_batch",
                    "data": [{
                        "task_id": task_id,
                        "image_base64": img_b64,
                        "mime_type": "image/jpeg",
                        "prompt": prompt,
                        "aspect_ratio": aspect,
                        "upscale_1080p": upscale,
                        "duration_seconds": duration,
                        "seed": -1,
                    }]
                }))
            else:
                # Text-to-video: prompt only
                await ws.send(json.dumps({
                    "event": "submit_video_prompt",
                    "data": {
                        "task_id": task_id,
                        "prompt": prompt,
                        "aspect_ratio": aspect,
                        "seed": -1,
                        "upscale_1080p": upscale,
                        "duration_seconds": duration,
                    }
                }))

            # Wait for result (up to 10 minutes)
            while True:
                raw = await asyncio.wait_for(ws.recv(), timeout=600)
                msg = json.loads(raw)
                event = msg.get("event", "")
                data = msg.get("data", {})

                if event in ("video_result",):
                    status = data.get("status", "")
                    if status == "success":
                        video_url = data.get("video_url")
                        encoded_video = data.get("encoded_video", "")
                        out_path = os.path.join(OUTPUT_DIR, f"{task_id}.mp4")

                        if video_url and str(video_url) != "None":
                            import urllib.request
                            urllib.request.urlretrieve(video_url, out_path)
                            out_path = _remove_veo_watermark(out_path)
                            return {"ok": True, "path": out_path}
                        elif encoded_video:
                            with open(out_path, "wb") as f:
                                f.write(base64.b64decode(encoded_video))
                            out_path = _remove_veo_watermark(out_path)
                            return {"ok": True, "path": out_path}
                        else:
                            return {"ok": False, "error": "No video data in result"}
                    else:
                        error = data.get("error", "Unknown error")
                        raw_data = data.get("raw", "")
                        return {"ok": False, "error": f"{error}\n{str(raw_data)[:300]}"}

                elif event == "error":
                    return {"ok": False, "error": str(data)}

                # Send ack for results
                if event == "video_result":
                    try:
                        await ws.send(json.dumps({
                            "event": "result_ack",
                            "data": {"task_id": data.get("task_id", task_id)}
                        }))
                    except:
                        pass

    # Run async WebSocket flow with retry
    max_retries = 3
    for attempt in range(max_retries):
        try:
            loop = asyncio.new_event_loop()
            result = loop.run_until_complete(_generate())
            loop.close()
            return result
        except asyncio.TimeoutError:
            return {"ok": False, "error": "Timeout waiting for video generation (10 min)"}
        except Exception as e:
            err = f"Nhungoc VEO3: {type(e).__name__}: {str(e)}"
            print(f"[Nhungoc] Attempt {attempt+1}/{max_retries} failed: {err}", flush=True)
            if attempt < max_retries - 1:
                time.sleep(3)
                continue
            return {"ok": False, "error": err}


def compose_final(video_path: str, quote: str, music_path: str = None,
                  logo_path: str = None, output_path: str = None, slow_motion: bool = False,
                  overlay_opacity: float = 0.0, trim_start: float = 0.0, trim_end: float = 0.0,
                  video_effect: str = "", effect_strength: float = 1.0,
                  music_trim_start: float = 0.0, music_trim_end: float = 0.0,
                  text_size: int = 100, text_weight: int = 500, text_position: int = 50,
                  text_font: str = "YuGothM.ttc",
                  slow_motion_mode: str = "blend",
                  slow_motion_factor: float = 0.7) -> dict:
    """Compose final video with text overlay, music, and logo using FFmpeg.

    slow_motion_mode: 'blend' (швидко), 'rife' (AI, CapCut-якість), 'mci' (старий)
    slow_motion_factor: 0.3..1.0 — speed multiplier (0.5 = 2x slower, 1.0 = normal)
    """
    ffmpeg = _find_ffmpeg()

    # Trim-first, then slow motion.
    # Причина: user обирає trim на ОРИГІНАЛЬНОМУ відео у таймлайні редактора.
    # Якщо спочатку застосувати slow — trim ріже вже-slow версію (6с замість 12с).
    # Правильно: trim 6с з оригіналу → slow 0.5x → 12с (користувач бачить довге відео).
    if slow_motion:
        sm_factor = max(0.3, min(1.0, float(slow_motion_factor)))

        # 1. Trim оригінал (якщо заданий) у тимчасовий файл
        if trim_end > trim_start + 0.5:
            trimmed_path = video_path.replace(".mp4", "_trim.mp4")
            trim_cmd = [
                ffmpeg, "-y",
                "-ss", f"{trim_start:.2f}",
                "-i", video_path,
                "-t", f"{(trim_end - trim_start):.2f}",
                "-c", "copy",
                trimmed_path,
            ]
            try:
                subprocess.run(trim_cmd, capture_output=True, text=True, timeout=60,
                               **_subprocess_low_priority_flags())
                if os.path.isfile(trimmed_path) and os.path.getsize(trimmed_path) > 1000:
                    video_path = trimmed_path
                    # Trim вже застосовано — скидаємо для наступного compose
                    trim_start = 0.0
                    trim_end = 0.0
            except Exception as e:
                print(f"[trim-before-slow] error: {e}", flush=True)

        # 2. Slow motion на trim'нутому (або оригіналі якщо trim не було)
        video_path = _apply_slow_motion(video_path, sm_factor, mode=slow_motion_mode)

    if not output_path:
        output_path = os.path.join(OUTPUT_DIR, f"final_{int(time.time())}.mp4")

    # Build filter complex
    filters = []

    # Scale video to 1080x1920 + bottom gradient (black fade from bottom)
    grad_height = 300
    # Video effect color grading with strength (0-1)
    effect_filter = ""
    s = min(max(effect_strength, 0), 1)
    def _lerp(a, b): return a + (b - a) * s
    if video_effect == "cinematic" and s > 0:
        effect_filter = f",eq=contrast={_lerp(1,1.15):.2f}:saturation={_lerp(1,0.85):.2f}:brightness={_lerp(0,-0.05):.3f}"
    elif video_effect == "cold_steel" and s > 0:
        effect_filter = f",eq=saturation={_lerp(1,0.3):.2f}:contrast={_lerp(1,1.2):.2f}:brightness={_lerp(0,-0.1):.3f},colorbalance=bs={_lerp(0,0.1):.2f}:bm={_lerp(0,0.05):.2f}"
    elif video_effect == "blood_ash" and s > 0:
        effect_filter = f",eq=saturation={_lerp(1,0.6):.2f}:contrast={_lerp(1,1.3):.2f}:brightness={_lerp(0,-0.15):.3f},colorbalance=rs={_lerp(0,0.08):.2f}:gs={_lerp(0,-0.03):.2f}"
    elif video_effect == "fog_ghost" and s > 0:
        effect_filter = f",eq=saturation={_lerp(1,0.2):.2f}:contrast={_lerp(1,0.9):.2f}:brightness={_lerp(0,0.1):.3f}"
    elif video_effect == "noir" and s > 0:
        effect_filter = f",eq=saturation={_lerp(1,0):.2f}:contrast={_lerp(1,1.4):.2f}:brightness={_lerp(0,-0.15):.3f}"

    scale_filter = f"[0:v]scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920{effect_filter}[scaled]"

    # Black overlay (0.0-0.8 opacity)
    if overlay_opacity > 0.01:
        ov_alpha = min(overlay_opacity, 0.8)
        scale_filter += f";color=black@{ov_alpha}:1080x1920:d=1[darkov];[scaled][darkov]overlay=0:0[withov]"
        grad_input = "[withov]"
    else:
        grad_input = "[scaled]"

    filters.append(
        f"{scale_filter};"
        f"color=black:1080x{grad_height}[gradbase];"
        "[gradbase]format=rgba,geq="
        f"a='clip(255*Y/{grad_height},0,255)'"
        ":r=0:g=0:b=0[grad];"
        f"{grad_input}[grad]overlay=0:H-{grad_height}[base]"
    )

    # Add logo overlay if provided
    if logo_path and os.path.isfile(logo_path):
        filters.append(f"[1:v]scale=120:-1,format=rgba,colorchannelmixer=aa=0.4[logo]")
        filters.append("[base][logo]overlay=W-w-40:H-h-40[withlogo]")
        text_input = "[withlogo]"
    else:
        text_input = "[base]"

    # Text overlay — two-line style matching competitor
    import shutil

    # Copy CJK font (supports kanji) to output dir
    font_filename = text_font or "YuGothM.ttc"
    font_copy = os.path.join(OUTPUT_DIR, font_filename)
    # Copy font from Windows\Fonts if not already in output dir
    if not os.path.exists(font_copy):
        font_src_path = os.path.join(r"C:\Windows\Fonts", font_filename)
        if os.path.isfile(font_src_path):
            shutil.copy2(font_src_path, font_copy)
        else:
            # Fallback to CJK font
            cjk = _find_cjk_font()
            if cjk:
                shutil.copy2(cjk, font_copy)
    font_param = f"fontfile={font_filename}:" if os.path.exists(font_copy) else ""

    # Parse quote into 3 lines (competitor style):
    # Format A: "鍛錬 / Tanren — the forge does not apologize"
    #   → kanji="鍛錬", romaji="TANREN", english="TO FORGE IS TO NOT APOLOGIZE."
    # Format B: "The dead ask nothing — walk on"
    #   → kanji="", romaji="", english="THE DEAD ASK NOTHING — WALK ON."
    ts = int(time.time())
    kanji = ""
    romaji = ""
    english = ""

    if " / " in quote:
        slash_idx = quote.index(" / ")
        kanji = quote[:slash_idx].strip()  # "鍛錬"
        after_slash = quote[slash_idx + 3:]  # "Tanren — the forge..."
        if " — " in after_slash:
            romaji = after_slash[:after_slash.index(" — ")].strip().upper()
            english = after_slash[after_slash.index(" — ") + 3:].strip().upper()
        else:
            romaji = after_slash.strip().upper()
    else:
        english = quote.strip().upper()

    # Add period at end if missing
    if english and not english.endswith(('.', '…')):
        english += '.'

    # Write text files for FFmpeg drawtext
    def _write_txt(text, suffix):
        fname = f"txt_{suffix}_{ts}.txt"
        fpath = os.path.join(OUTPUT_DIR, fname)
        with open(fpath, "w", encoding="utf-8") as f:
            f.write(text)
        return fname

    def _escape_ffmpeg(text):
        """Escape text for FFmpeg drawtext text= parameter."""
        return text.replace("\\", "\\\\").replace("'", "'\\\\\\''").replace(":", "\\:").replace("%", "%%")

    # Text overlay with customizable size, weight, position
    # text_size: 100 = default, text_position: 50 = center
    # Preview is 240px wide, video is 1080px → base sizes scaled for 1080px
    scale = text_size / 100.0
    kanji_fs = int(120 * scale)
    romaji_fs = int(52 * scale)
    eng_fs = int(36 * scale)
    # text_position (20-80) maps to y position
    pos_base = text_position / 100.0  # 0.2 to 0.8

    text_filters = []
    current_input = text_input
    line_num = 0

    if kanji:
        fk = _write_txt(kanji, "kanji")
        text_filters.append(
            f"{current_input}drawtext="
            f"{font_param}"
            f"textfile={fk}:"
            f"fontsize={kanji_fs}:"
            f"fontcolor=white:"
            f"x=(w-text_w)/2:"
            f"y=h*{pos_base - 0.07:.2f}-text_h/2:"
            f"borderw=0:"
            f"line_spacing=0"
            f"[txt{line_num}]"
        )
        current_input = f"[txt{line_num}]"
        line_num += 1

    if romaji:
        fr = _write_txt(romaji, "romaji")
        text_filters.append(
            f"{current_input}drawtext="
            f"{font_param}"
            f"textfile={fr}:"
            f"fontsize={romaji_fs}:"
            f"fontcolor=white:"
            f"x=(w-text_w)/2:"
            f"y=h*{pos_base - 0.02:.2f}:"
            f"borderw=0"
            f"[txt{line_num}]"
        )
        current_input = f"[txt{line_num}]"
        line_num += 1

    if english:
        fe = _write_txt(english, "eng")
        text_filters.append(
            f"{current_input}drawtext="
            f"{font_param}"
            f"textfile={fe}:"
            f"fontsize={eng_fs}:"
            f"fontcolor=white@0.90:"
            f"x=(w-text_w)/2:"
            f"y=h*{pos_base + 0.03:.2f}:"
            f"borderw=0"
            f"[txt{line_num}]"
        )
        current_input = f"[txt{line_num}]"
        line_num += 1

    # Rename last output to [final]
    if text_filters:
        last = text_filters[-1]
        text_filters[-1] = last.rsplit('[', 1)[0] + '[final]'
        filters.append(";".join(text_filters))
    else:
        filters.append(f"{text_input}copy[final]")

    filter_complex = ";".join(filters)

    # Записуємо фільтр у файл — уникаємо проблем з екрануванням шляхів Windows
    filter_script = os.path.join(OUTPUT_DIR, f"filter_{int(time.time())}.txt")
    with open(filter_script, "w", encoding="utf-8") as fs:
        fs.write(filter_complex)

    # Build command
    cmd = [ffmpeg, "-y"]

    # Trim: -ss before -i (fast seek), -t after -i
    if trim_start > 0.1:
        cmd += ["-ss", f"{trim_start:.2f}"]
    cmd += ["-i", video_path]
    if trim_end > trim_start + 0.5:
        duration = trim_end - max(trim_start, 0)
        cmd += ["-t", f"{duration:.2f}"]

    if logo_path and os.path.isfile(logo_path):
        cmd += ["-i", logo_path]

    if music_path and os.path.isfile(music_path):
        if music_trim_start > 0.1:
            cmd += ["-ss", f"{music_trim_start:.2f}"]
        cmd += ["-i", music_path]
        if music_trim_end > music_trim_start + 0.5:
            pass  # duration handled by -shortest

    cmd += ["-filter_complex_script", filter_script]
    cmd += ["-map", "[final]"]

    # Audio: mix original + music, or just music
    if music_path and os.path.isfile(music_path):
        audio_idx = 2 if (logo_path and os.path.isfile(logo_path)) else 1
        cmd += ["-map", f"{audio_idx}:a"]
    else:
        # Try to keep original audio
        cmd += ["-map", "0:a?"]

    cmd += _video_encoder_args(crf=23)
    cmd += ["-c:a", "aac", "-b:a", "192k"]

    # Обмежуємо output ТОЧНО до тривалості відео (з врахуванням trim).
    # Раніше було -shortest + -t 60: коли музика довша за відео, FFmpeg
    # дублював останній frame щоб дотягнути audio → freeze frame в кінці.
    # Тепер: ffprobe → effective video duration → -t забороняє писати довше.
    # Аудіо автоматично обрізається до output duration.
    video_duration = _get_video_duration(video_path)
    if trim_end > trim_start + 0.5:
        # trim вже застосовано через -ss/-t у video input → effective = trim_end-trim_start
        effective_duration = min(video_duration or 60.0, trim_end - trim_start)
    else:
        effective_duration = video_duration or 60.0
    # Hard cap 60s (slow motion 0.3x може зробити дуже довге відео)
    effective_duration = min(effective_duration, 60.0)
    if effective_duration > 0.1:
        cmd += ["-t", f"{effective_duration:.2f}"]
    else:
        cmd += ["-t", "60"]  # fallback якщо ffprobe не спрацював

    # CapCut metadata spoofing — змушуємо IG думати що файл експортовано CapCut.
    # Ці format-level tags з реального CapCut-экспорту є унікальними для нього.
    cmd += [
        "-metadata", "Hw=1",
        "-metadata", "bitrate=12000000",
        "-metadata", "maxrate=0",
        "-metadata", "te_is_reencode=1",
        "-metadata", "encoder=Lavf61.1.100",
        # major_brand/compatible_brands задаються через movflags/brand але FFmpeg сам ставить isom+avc1mp41
        "-movflags", "+faststart",
    ]

    cmd += [output_path]

    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=120, cwd=OUTPUT_DIR,
            **_subprocess_low_priority_flags(),
        )
        if result.returncode != 0:
            return {"ok": False, "error": f"FFmpeg error: {result.stderr[-500:]}"}
        return {"ok": True, "path": output_path}
    except subprocess.TimeoutExpired:
        return {"ok": False, "error": "FFmpeg timeout"}
    except FileNotFoundError:
        return {"ok": False, "error": "FFmpeg не знайдено. Встановіть FFmpeg."}


def _wrap_text(text: str, max_chars: int = 25) -> str:
    words = text.split()
    lines = []
    current = ""
    for word in words:
        if current and len(current) + 1 + len(word) > max_chars:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}" if current else word
    if current:
        lines.append(current)
    return "\n".join(lines)


# ===== FULL PIPELINE =====

def run_pipeline(params: dict):
    """Generator that yields progress updates as JSON-serializable dicts."""
    style = params.get("style", "Воїн")
    prompt = params.get("prompt", "")
    quote = params.get("quote", "")
    music_path = params.get("music_path")
    logo_path = params.get("logo_path")
    image_provider = params.get("image_provider", "stability")
    image_api_key = params.get("image_api_key", "")
    video_provider = params.get("video_provider", "kling")
    video_api_key = params.get("video_api_key", "")

    # Step 1: Generate image
    yield {"step": "image", "status": "started", "message": "Генерація зображення..."}

    img_result = generate_image(prompt, style, image_provider, image_api_key)
    if not img_result.get("ok"):
        yield {"step": "image", "status": "error", "message": img_result.get("error")}
        return

    image_path = img_result["path"]
    yield {"step": "image", "status": "done", "path": image_path, "message": "Зображення готове"}

    # Step 2: Generate video
    yield {"step": "video", "status": "started", "message": "Генерація відео (може зайняти 1-3 хвилини)..."}

    vid_prompt = f"{style} warrior, {EPIC_VIDEO_SUFFIX}"
    vid_result = generate_video(image_path, vid_prompt, video_provider, video_api_key)
    if not vid_result.get("ok"):
        yield {"step": "video", "status": "error", "message": vid_result.get("error")}
        return

    video_path = vid_result["path"]
    yield {"step": "video", "status": "done", "path": video_path, "message": "Відео згенеровано"}

    # Step 3: Compose final
    yield {"step": "compose", "status": "started", "message": "Складання фінального відео..."}

    final_result = compose_final(video_path, quote, music_path, logo_path)
    if not final_result.get("ok"):
        yield {"step": "compose", "status": "error", "message": final_result.get("error")}
        return

    yield {"step": "compose", "status": "done", "path": final_result["path"], "message": "Готово!"}
